baseurl = "https://dmac.netlify.com"
languageCode = "en-us"
title = "ETC1010: Data Modelling and Computing"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Textbook"
    url = "http://r4ds.had.co.nz"
    weight = 2
[[menu.main]]
    name = "ED (Discuss, Ass'ts & quizzes)"
    url = "https://edstem.com.au"
    weight = 3
[[menu.main]]
    name = "DataCamp"
    url = "https://www.datacamp.com"
    weight = 4
[[menu.main]]
    name = "Unit guide"
    url = ""
    weight = 5

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Di Cook](https://dicook.org) 2017-9 | [Github](https://github.com/dicook) | [Twitter](https://twitter.com/dicook)"
