baseurl = "https://dmac.netlify.com"
languageCode = "en-us"
title = "ETC1010: Data Modelling and Computing"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Textbook"
    url = "http://r4ds.had.co.nz"
    weight = 2
[[menu.main]]
    name = "ED (Discuss, Ass'ts & quizzes)"
    url = "https://edstem.org/courses/3645"
    weight = 3
[[menu.main]]
    name = "Unit guide"
    url = "https://unitguidemanager.monash.edu/view?unitCode=ETC1010&tpCode=S2-01&tpYear=2019"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Di Cook](https://dicook.org) 2017-9 & &copy; [Nick Tierney](https://njtierney.com) 2019  | [Github](https://github.com/njtierney) | [Twitter](https://twitter.com/nj_tierney)"
